spring:
  application:
    name: "lms"
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: development
  h2:
    console:
      enabled: true
      path: /h2-console