spring:
  application:
    name: "lms"
  datasource:
    url: ${vcap.services.lms-hdi.credentials.url}
    username: ${vcap.services.lms-hdi.credentials.user}
    password: ${vcap.services.lms-hdi.credentials.password}
    driver-class-name: com.sap.db.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      ddl-auto: none
      dialect: org.hibernate.dialect.HANAColumnStoreDialect
      hibernate:
        default_schema: ${vcap.services.lms-hdi.credentials.user}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: hana
management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers
  endpoint:
    health:
      show-details: always

smtp-ups:
  host: ${vcap.services.lms-ups.credentials.host}
  port: ${vcap.services.lms-ups.credentials.port}
  username: ${vcap.services.lms-ups.credentials.mail}
  password: ${vcap.services.lms-ups.credentials.password}
feature-flag:
  uri: ${vcap.services.lms-flag.credentials.uri}
  username: ${vcap.services.lms-flag.credentials.username}
  password: ${vcap.services.lms-flag.credentials.password}