spring:
  application:
    name: "lms"
  datasource:
    url: jdbc:postgresql://localhost:5432/lmsdb
    username: lmsuser
    password: lmspassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: postgres
management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers
  endpoint:
    health:
      show-details: always
info:
  app:
    name: Course Management API
    version: 1.0.0
mailtrap:
  inbox-id: 3713999
  token: bd8414f579199eda58f71a2eb166114a
  sandbox: true
  from-mail: example@leverx.com
  from-name: LeverX