databaseChangeLog:
  - changeSet:
      id: 2
      author: admin
      changes:
        - createTable:
            tableName: course_settings
            columns:
              - column:
                  name: id
                  type: VARBINARY(16)
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: start_date
                  type: TIMESTAMP
              - column:
                  name: end_date
                  type: TIMESTAMP
              - column:
                  name: is_public
                  type: BOOLEAN